DROP DATABASE IF EXISTS feedMeDb;
CREATE DATABASE feedMeDb;



USE feedMeDb;
CREATE TABLE recipes (
    id INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    url VARCHAR(400) NOT NULL,
    day VARCHAR(100) NOT NULL,
    time VARCHAR(10) NOT NULL,
    primary key(id)
)